### ISSUE TITLE
Visual Studio work

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#287]
In VS _CMakeLists.txt_ appears in the solution explorer. In v2.8 If a file was added to the source code _CMakeLists.txt_ could be updated and the plugin compiled again.

With SD3.0 the user would need to open _Plugin.cmake_ to edit the list of source files.

Bit of a trade off. I can live with this but it does not conform to how people normally use VS. Have we created a problem just for the convenience of using _update-templates_? Could Plugin.cmake be dropped in favour of a distinct module inside _CMakeLists.txt_.

**Comment by leamas** [comment]
Yes, it's a trade-off. 

Actually, adding source file is just an example.A plugin developer will  basically never change CMakeLists.txt but instead Plugin.cmake. The idea is that CMakeLists.txt is sort of constant.

We should take our time here. 

When you talk about update-templates I think this is somehow not that important. The point is that any update process, update-templates/manual/whatever, still is much easier if there is a difference between files maintained locally (Plugin.cmake) and centrally (CMakeLists.txt).  That is, it's easier and less error-prone to copy files instead of editing them.

Which boils down to a trade-off between the hassles of editing Plugin.cmake instead of CMakeLists.txt vs a safe, sound base for updating plugins. Expressed in those terms, the current solution seems like the right thing to me. That is not to say I'm sure.

Would a simple comment in CMakeLists.txt about Plugin.cmake make the current solution  more attractive (less awful?) for VS users?

**Comment by Rasbats** [comment]
Yes ... the convenience of editing _Plugin.cmake_ rather than fighting with _CMakeLists.txt_ is a big bonus. I will make a note for VS users in _CMakeLists.txt_.
