### ISSUE TITLE
Plugin version designation for master and beta.

### ISSUE THREAD

**Issue by Hakansv** [Rasbats/shipdriver_pi#349]
For a master plugin the version designation ${PLUGIN_API_NAME}-${VERSION_MAJOR}.${VERSION_MINOR} would be sufficient.
For the beta version the ${_build_id}.${_gitversion}") may be feasible to include.
My suggestion is next plugin template would reflect that,
Discussed here: https://github.com/Hakansv/ais-vd_pi/issues/1#issuecomment-991922707

![bild](https://user-images.githubusercontent.com/7202854/145723850-5e23ec6c-445c-4fa5-a658-d793d5677e7d.png)

**Comment by leamas** [comment]
Ack, this has actually been under way earlier but was lost, probably sine no one filed a bug.

"master plugin" refers to a regular, non-beta tag,right?

**Comment by Hakansv** [comment]
> "master plugin" refers to a regular, non-beta tag,right?

Right! Empty like this: set(PKG_PRERELEASE "")  # Empty, or a tag like 'beta'

**Comment by leamas** [comment]
Hm... let's try to sort this out. The version used is governed by the git tag, if any. A suggestion could be
  - Untagged builds keeps the current version which is major.minor.patch[.tweak][-pkg_prerelease]+build id.hash. Examples includes 5.2.2+123.deadbee and 5.2.2.1-beta1+123.deadbee if PKG_PRERELEASE is set.
  - Builds tagged with a tag like v5.2.2_beta1 gets a version which is v5.2.2_beta1. The same applies for all tags, the version used is the tag.
 
PKG_PRERELEASE will in this scheme only be used together with the rest of the version in untagged builds, like 5.2.2-beta1+123.deadbee

In the end, developer must use sound  principles when tagging. One important criteria is that new releases are sorted after older ones -- this sets some requirements on how tags should be numbered.

Thoughts?

**Comment by leamas** [comment]
BTW, and part of this game:  The metadata XML file contains more elaborated build info. For circleCI and some other builders this is a link to the build logs. It's available as a comment in the top of the file.

That is, even if we drop the build info from the version we can still trace the actual build, should it be necessary.

**Comment by Hakansv** [comment]
I may have got something wrong again than?
ais-vd_pi had a Tag on the build for the actual release but still like the picture on the first post. 
Compare the gitk shot below. Should I've made the Tag in another way?
![bild](https://user-images.githubusercontent.com/7202854/145728417-5a326add-3897-4c72-9fad-c7f44ab40e9c.png)

**Comment by Hakansv** [comment]
About the version number logic. My view:
All, not beta, releases, with or without Tag?, do not need more than what's for the oeSENC_pi on the picture above.
Beta can have more since some don't like to update version for all builds. But I myself can very well update version for all tests. But here we have different views.

**Comment by leamas** [comment]
The point is that according to what I propose, and partly already today, it doesn't matter if you update the version in Plugins.cmake or not. The version used when creating tarballs and metadata  is the git tag, which does not depend on the version in Pluigin.cmake. Practically, this implies the following workflow.

  1) Set the upcoming version, the one you plan to eventually release, in Plugins.cmake. Let's say it's 5.2.3
  2) Make builds which you test using Import Plugin. These needs no other  version  than the default which is something like 5.3.3+123.deadbee. As long as it is unique, it's fine
 3) At some point you start beta testing, probably by publishing in the beta catalog. You tag the first version you want to publish with the tag v5.2.3-beta1 which is the version used in the plugin catalog etc.
4) After some more beta tests you eventually produce the version you want to publish in the main catalog. Yoi commit this one and tag it with v5.2.3 which is the version used in the catalog 

As you see,  during this process Plugin.cmake is not updated at all. New versions are created using git tags. 

Thoughts?

**Comment by leamas** [comment]
>  is-vd_pi had a Tag on the build for the actual release but still like the picture on the first post.

If so, it is a bug which should be fixed. Can you link to the build?

**Comment by Hakansv** [comment]
My thoughts:
No I don't agree.
Referring to a not readable, impossible to remember and impractical number series like the Git number for yourself or with other is not feasible. 
All we need is version 1.0 then version 1.1. While working to version 1.2 the (beta) versions are 1.1.1-999. As simple as that. Easy to understand and speak about.
The Git number series is for Git to be able keep its history. Four us is the patch number enough and understandable.

Håkan

**Comment by Hakansv** [comment]
> Can you link to the build?

The version with "ais-vd-1.2...." at [Cloudsmith](https://cloudsmith.io/~opencpn/repos/ais-vd-alpha/packages/) are from the tagged build.
The latest Cloudsmith version 1.3... are from the branch "mytest" and are not using (beta) since that branch is intended to be used by me for copying to other machines. Why builds from other branches than master or beta need to show up in Cloudsmith I don't know?

**Comment by leamas** [comment]
It would be somewhat easier if you could provide a link to the circleci or appveyor build. I will dive into what I think is a bug later. The important issue is how we actually want things to be.

First: git hashes, hex digits like deadbee or fa1afe1  are of course useless as versions and I don't propose that. So lets take this off the table.

Using git tags a version scheme like the one propose 1.1.1.1 .. 1.1.1.999 ending up in a release version 1.2 certainly can be used.

The difference, perhaps, is how to create these versions. I guess you think about modifying Plugins.cmake for each release. What I propose is that you use a fixed version like 1.1 in Plugins.cmake and then adds git tags like v1.1.1.12 or v1.1.1.78 to commits when you want to test them in a wider audience. These tags will then be the version.

Another variant would be update the version in Plugin.cmake. But the question then becomes how to handle the +111.deadbee part a. k. a. the buildinfo. As long as there are no tags it is required to make each build unique, but we don't want it, well, exactly when do we don't want it in this scheme? A setting in Plugin.cmake which disables the buildinfo completely, leaving the responsiblity to make each build unique to the dev? Seems scary to me.

Also, relying on the version in Plugin.cmake we still needs tags to be able to find out the repo (alpha/beta/release) to use. And since we still need a tag, we need the version in both Plugin.cmake **and** the tag. We certainly don't wan't that.

Thoughts?

**Comment by leamas** [comment]
Please don't worry that much about builds "showing up" in Cloudsmith. Unstable/alpha is basically just  a scratch repo used to verify that the build chain works. No sane end user uses builds from this repo, and nothing there is in the catalog. It is just a test dumping ground.

**Comment by Hakansv** [comment]
Links to  version 1.2 builds: (Tagged as v1.2.0) 
[Windows](https://ci.appveyor.com/project/Hakansv/ais-vd-pi/builds/41846873)
[flatpack](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi/13/workflows/b0b12e15-eb92-40c9-b717-758ca3a86aa1/jobs/136)

About version numbering. My insight in all this is limited. My simple view is clear although not nailed. I've asked @keesverruijt  to share his experience from plugins and development. Let's see if he has the time.

**Comment by leamas** [comment]
Ah... thanks for those links. Looking at these, it seems that we are partly talking about different things.

I have mostly been thinking about the names of tarballs and also metadata files. But these names are actually ok, they use the _v1.2.0_ tag instead of version have no build info like +123.deadbee.

But, if I  get it right this time, you refer to the version displayed in the GUI. This is actually the version in the catalog which comes from the metadata files. So the bug you describe is really that the metadata version handling when using tags is inconistent, not matching how tarballs and metadata is named.

**Comment by leamas** [comment]
@keesverruijt  is indeed  very welcome here. 

That said, for now I will focus on getting the version displayed in the GUI correct, hopefully without breaking any eggs w r t tarball and metadata naming.

**Comment by Hakansv** [comment]
@leamas 
Tarball numbering and designation is not any concern. 
As you noticed I'm talking about what the users find at the Plugins page and and other locations where plugin version are shown. As of my picture in the first post here.

I'll try your patch to metadata.cmake

Thanks
Håkan

**Comment by leamas** [comment]
This is the patch currently in master branch as 45f6db9. It seems to work, the version in the metadata is exactly the tag when it exists.

```
diff --git a/cmake/Metadata.cmake b/cmake/Metadata.cmake
index 556303d..7a25e4b 100644
--- a/cmake/Metadata.cmake
+++ b/cmake/Metadata.cmake
@@ -109,7 +109,11 @@ set(_pre_rel ${PKG_PRERELEASE})
 if (NOT "${_pre_rel}" STREQUAL "" AND _pre_rel MATCHES "^[^-]")
   string(PREPEND _pre_rel "-")
 endif ()
-set(pkg_semver "${PROJECT_VERSION}${_pre_rel}+${_build_id}.${_gitversion}")
+if ("${_git_tag}" STREQUAL "")
+  set(pkg_semver "${PROJECT_VERSION}${_pre_rel}+${_build_id}.${_gitversion}")
+else ()
+  set(pkg_semver "${_git_tag}")
+endif ()
 
 # pkg_displayname: GUI name
 if (ARCH MATCHES "arm64|aarch64")
@@ -128,12 +132,8 @@ string(APPEND pkg_displayname
 set(pkg_xmlname ${pkg_displayname})
 
 # pkg_tarname: Tarball basename
-if ("${_git_tag}" STREQUAL "")
-  set(pkg_tarname "${PLUGIN_API_NAME}-${pkg_semver}")
-else ()
-  set(pkg_tarname "${PLUGIN_API_NAME}-${_git_tag}")
-endif ()
-string(APPEND pkg_tarname
+string(CONCAT pkg_tarname
+  "${PLUGIN_API_NAME}-${pkg_semver}"
   "_${plugin_target}-${plugin_target_version}-${_pkg_arch}"
 )
 

```

**Comment by leamas** [comment]
@Hakansv:   As I understand it, the patch in master solves your problem, right? If so, is it time to close this bug?

**Comment by Hakansv** [comment]
Yes it did. But since we had different views on the version number series during the update from one release to another we may await input from Kees. He was heavily busy today but planned to join tomorrow.
My view is like 1.2.0 > 1.2.1 > 1.2.2 (beta) > ...... > 1.2.15 (beta) .... > 1.3.0

**Comment by leamas** [comment]
There are many ways to do this, that is one.

Another scheme  (which I happen to know Kees is using) heading for the 1.3.0 release is 1.3.0-beta1 followed by 1.3.0-beta2 etc.  with a final 1.3.0 release. This is a really widely used scheme, sometime using -rc1, , -rc2 etc. instead of beta1, sometimes with 1.3.0-alpha[1-9]  preceding the betas.

**Comment by Hakansv** [comment]
All seems like personal views. So I'll follow our main OCPN scheme also for plugins, like beta 5.5.1 - 9999 -> Released 5.6.0
Thanks
Håkan

**Comment by leamas** [comment]
Fair enough. And since nothing stops you from doing so: could we close this bug?

**Comment by leamas** [comment]
Aouch... sorry
