### ISSUE TITLE
Converting a legacy plugin - update-templates failed to copy config.h.in

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#405]
As per the title.
Plugin being worked on was SailawayNMEA_pi.

**Comment by Rasbats** [comment]
_COPYING_ was also not copied across from ShipDriver.

**Comment by leamas** [comment]
COPYING can absolutely not be copied. This is legal stuff, and determining the license must be done with some thought. Perhaps need some documentation, though (?)

config.h.in is a special case: It should be copied if it does not exist, but otherwise not -- this is local configuration. Should be fixed.

**Comment by leamas** [comment]
Same thing. This is basically plugin-dependent stuff which could (should?) be copied if it does not exist, but otherwise not. 

There might be more like this...

**Comment by Rasbats** [comment]
CircleCI builds are here:
[https://app.circleci.com/pipelines/github/Rasbats/SailawayNMEA_pi](https://app.circleci.com/pipelines/github/Rasbats/SailawayNMEA_pi)

A lot of errors that I am working on. Not yet finished with my source code.

**Comment by leamas** [comment]
DECL_IMP etc are declared in ocpn_plugin.h, you need to include it....
