### ISSUE TITLE
New plugin ABIs for 5.8.0

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#458]
The upcoming 5.8.0 version will use a different set of ABIs compared to current status. This is partly because of using wxWidgets 3.2 and partly due to the "use debian plugins on ubuntu [roadmap](https://github.com/OpenCPN/OpenCPN/discussions/2502#discussioncomment-1904180)"

The set of plugins to use is described in the top comment of https://github.com/OpenCPN/OpenCPN/discussions/2797. Since this affects all plugins build chains, please keep discussions on what to build in that discussion.

**Comment by leamas** [comment]
As of now, parts of this is blocked on https://github.com/OpenCPN/plugins/pull/747

**Comment by leamas** [comment]
I have updated the wxsvg package, needs help with uploading. Don't  know how long time it could take.

Also need to publish a new opencpn package linked to wx3.2. This will be the alpha build, made available on the Flatpak beta branch. Good night.

**Comment by Rasbats** [comment]
For flatpak I needed to change SDK//20.08 to 22.08 in ci/circleci-build-flatpak.sh. Everything now builds. Great work again. Thanks.

All builds complete but a Windows test causes O to crash. In case this was due to wxsvg I tested by replaceing the wxsvg library by target_compile_definitions. Still get a crash. Maybe I need to wait for part 2. Reverting the test.

**Comment by Rasbats** [comment]
I messed up. Changed API to 17 and did not change src code 6 days ago. Will revert to 16 and see what happens.

**Comment by leamas** [comment]
I think we have everything in place: windows,macos, debian, flatpak.  If there are problems, let's file separate issues. Closing this.
