### ISSUE TITLE
Ubuntu-18.04 Two tarball versions of ShipDriver

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#72]
On Cloudsmith two versions of the Ubuntu-18.04 tarball are found.

**ShipDriver-ubuntu-18.04-tarball** 
#1  2.5.52+1182.v2.5.52 
#2  2.5.52+1181.v2.5.52 

Both have the same download filename ending: v2.5.52_ubuntu-18.04-x86_64.tar.gz

After updating the plugin catalog and trying to install the plugin automatically the message "... plugin is not compatible with this version of ..." appears.

Importing the 1181 version and the plugin works. Importing 1182, which is what is in the catalog (?) does not work.

(Same problem using the same CI process with UKTides)

**Comment by Rasbats** [comment]
The GTK3 version seems to be missing for xenial. Is this linked with the script problem?

**Comment by Rasbats** [comment]
Metadata xml for my non-GTK3 system has picked up the wrong name?

**Comment by leamas** [comment]
For xenial/16.04, it's IMHO no point making a gtk3 version; here gtk2 is what's used.

As for bionic/18.04 we do need to make both gtk2 and gtk3 versions, this is the transition window. From 20.04/focal we only make gtk3 out of necessity, since all gtk2 libs are dropped,

It looks like the gtk3 build doesn't get the correct name  ending in _ubuntu-gtk3-18.04-x86_64.tar.gz_. Instead, it uses *ubuntu-18.04-x86_64.tar.gz*. This is what I see in the circleci build logs.

Furthermore, in the catalog there is only one version for ubuntu/18.04 while there should be two (gtk2 and gtk3).

@rasbats: when you are testing on bionic, are you using the default gtk2 opencpn version? (gtk3 builds are also available).

**Comment by leamas** [comment]
hm... @rasbats: Can you provide a link to the official builds on circleci which eventually are used in the catalog?

**Comment by leamas** [comment]
I have found the error  (knock, knock...)  It's about Metadata.cmake and PluginSetup.cmake. Basically, PluginSetup is invoked at an early stage before the wxWidgets libs are located. SInce these are used to determine if this is a gtk3 build, the test fails and everything is built as gtk2.

Going to bed now. Will try to make a PR tomorrow.

**Comment by Rasbats** [comment]
Alec... I am running Bionic gtk2 here. 
Will test this commit locally. 
Issue left open until I update the master catalog.

**Comment by leamas** [comment]
OK, that's what I guessed. I have only tested to the point that the `<target>` is set to ubuntu-gtk3 when applicable.

You can check what you actually have in a tarball by downloading it, unpack it (tar -xf) and then use ldd, something like *ldd ShipDriver-ubuntu-18.04/lib/opencpn/libShipDriver\_pi.so | grep gtk3*.

**Comment by leamas** [comment]
hm... back after a night's sleep I need i amend to this PR. It should not affect your testing, it about a special case. Please stay tuned.

**Comment by leamas** [comment]
> Issue left open until I update the master catalog.

Seems fine, more testing is indeed required.
